



version: '3'
services:
  eCommerceDbService:
    image: postgres:14.3
    restart: always
    ports: 
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    container_name: eCommerceDb
    volumes:
      - ./postgres-db-volume-eCommerce:/var/lib/postgresql/data
      